#arrays


apresentacao=(
	"Meu nome é Lucifer, sou um robo criado pelo Ramone, e estou aqui para servi-lo!!"
	"Oi sou Lucifer, você deve ser o $USER podemos ser amigos?"
	"Me chamo Lucifer, mas não sou o tal de Morning Star da serie, sou apenas um robô hacker, em que posso ajudar??"
	"Calma eu não sou do mal, apenas um hacker e estou aqui para lhe ajudar, me chamo Lucifer!!"

)

oi=(
	"Olá, $USER tudo bem?"
	"Oiiiiiiiiii"
	"Ola hacker"
	"Ola, meu amigo."
	"Eae tudo em cima??"
)


bom_dia=(
	"Ola Bom Dia $USER"
	"Bom dia amigo"
	"Bom dia chefia, meu nome é Lucifer"
	"Bom dia é um prazer falar com você!!"
	"Bom dia, ja tomou seu café?"
	"Bom dia seja muito bem-vindo!!"
)


boa_noite=(
	"Hey $USER oque faz acordado??"
	"Boa noite, como posso ajudar??"
	"Tenha uma otima noite!!"
)


san=(
	"Eu torço para o Santos Futebol Clube"
	"O Santos é o time da virada"
	"Dalhee peixe"
	"SAAAAANTOOOOS!!!!"
)

palm=(
	"O Palmeiras não tem mundial!!!"
	"51 é pinga"
	"AU AU AU GUARANI DA CAPITALLLL"
)

gamba=(
	"Corinthians gambazada"
	"Hey galinha preta vaaai tomar no cu, 8 pedaladas, segunda divisão, 11 anos de tabu!!!"
	"2000 é do Boca"
)

cheiro=(
	"87 é do Sport"
	"CHEEEIRINHOOO!!!"
	"Mulambadaaa fdp"
)

musica=(
	"I Saw you Say - Raimundos"
)



#end_arrays
