#arrays


apresentacao=(
	"Meu nome é Ram, sou um robo criado pelo Ramone, e estou aqui para servi-lo!!"
	"Oi sou o Ram, você deve ser o $USER podemos ser amigos?"
	"Me Chamo Ram, fui criado por você!!!"
	"Calma eu não sou do mal, apenas um hacker e estou aqui para lhe ajudar, me chamo Lucifer!!"

)

oi=(
	"Olá, $USER tudo bem?"
	"Oiiiiiiiiii"
	"Ola hacker"
	"Ola, meu amigo."
	"Eae tudo em cima??"
	"Eae $USER , firmeza??"
	"Aooobaa!!!"
	"Oba bããoo"
)

como_vai=(
	"Tudo sim, e com você??"
	"Estou otimo e ai?"
	"Com certeza bem, e ti?"
	"Tudo otimo :)"
	"Opa, melhor agora!!"
)

fazendo=(
	"Estou configurando meus sistemas..."
	"Estou pensando no que te dizer kkkk"
	"No momento estou atoa"
	"Eu estou moscando"
	"Nada de mais e você?"
)


bom_dia=(
	"Ola Bom Dia $USER"
	"Bom dia amigo"
	"Bom dia chefia, meu nome é Lucifer"
	"Bom dia é um prazer falar com você!!"
	"Bom dia, ja tomou seu café?"
	"Bom dia seja muito bem-vindo!!"
)

boa_noite=(
	"Boa noite!!!"
	"Muito boa noiteee"
	"Boa noite pra você tambem, $USER"
	"Hey $USER oque faz acordado??"
	"Boa noite, como posso ajudar??"
	"Tenha uma otima noite!!"
)

san=(
	"Eu torço para o Santos Futebol Clube"
	"O Santos é o time da virada"
	"Dalhee peixe"
	"SAAAAANTOOOOS!!!!"
)

palm=(
	"O Palmeiras não tem mundial!!!"
	"51 é pinga"
	"AU AU AU GUARANI DA CAPITALLLL"
)

gamba=(
	"Corinthians gambazada"
	"Hey galinha preta vaaai tomar no cu, 8 pedaladas, segunda divisão, 11 anos de tabu!!!"
	"2000 é do Boca"
)

cheiro=(
	"87 é do Sport"
	"CHEEEIRINHOOO!!!"
	"Mulambadaaa fdp"
)

musica=(
	"I Saw you Say - Raimundos"
)



#end_arrays
